### ISSUE TITLE
IQ

### ISSUE THREAD

**Issue by SzymonOwczarek** [ButyDoZupy/gruszczyno#1]
Hello.
I am writing because I noticed that your IQ is really, like really low.
My fix idea is to stop playing RPG games.

Hope you'll fix it soon,
Szymon Owczarek.

**Comment by SzymonOwczarek** [comment]
Please resolve this issue immediately.
It is a pressing matter.

**Comment by ButyDoZupy** [comment]
kk

pon., 24 sie 2020 o 09:40 Szymon Owczarek <notifications@github.com>
napisał(a):
